# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [ 11, 17 ]  # (open)JDK releases
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up openJDK version
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install Dependencies
      run: npm install -g ro-crate-html-js
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        # - name: Execute Gradle test
        #run: ./gradlew test --tests PreviewTest
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results (Gradle ${{ matrix.jdk }})
        path: build/reports/jacoco/test/jacocoTestReport.xml

  publish-test-results:
    name: "Publish Test Results"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Test Coverage Results
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: "artifacts/jacocoTestReport.xml"
          token: ${{ secrets.GITHUB_TOKEN }}

